name: Hadolint

on:
  push:

jobs:
  hadolint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0

    - name: Lint Dockerfile
      uses: hadolint/hadolint-action@v1.6.0
      with:
       dockerfile: ../Dockerfile
